train_config:
  max_epoch : 6
  spilt : 0.95
  num_samples : null
  lm_lr : 1.e-5
  agent_lr : 0.e-5
  betas: [0.8, 0.998]
  weight_decay : 0.01
  topk : 1
  load_E : True
  use_prefix : True

Enc_config:
  enc_lr : 3.e-4
  groups : 1
  num_layers : 16
  num_prefix : 8

Enc_size_config:
  num_hidden_layers: 6
  num_attention_heads: 8
  hidden_size: 768
  intermediate_size: 3072

lex:
  pre_lr : 5.e-5
  fine_lr : 1.e-5
  betas: [0.9, 0.999]
  weight_decay : 0.01
  share_param : True

loader_config:
  batch_size : 2
  shuffle : True
  num_workers : 1
  persistent_workers : True



cluster_config:
  k: 3000
  bs: 200000
  lr: 0.5
  tol: 0.05
  num_search: 4
  k_sparse: 64

data_config:
  num_doc: 200000
  num_samples: 100000
  windows: 192
  step: 128

generate_config:
  no_repeat_ngram_size: 6
  do_sample: False
  temperature: null
  top_p: null
  top_k: null
  num_beams: 1
  bad_words_ids: null




seed: 87
