train_config:
  max_epoch : 6
  spilt : 0.95
  num_samples : null
  enc_lr : 1.e-5
  lm_lr : 1.e-5
  agent_lr : 5.e-5
  betas: [0.8, 0.998]
  weight_decay : 0.01
  topk : 1
  head : 2
  load_E : True
  use_prefix : True

lex:
  pre_lr : 5.e-5
  fine_lr : 1.e-5
  betas: [0.9, 0.999]
  weight_decay : 0.01
  share_param : True

loader_config:
  batch_size : 2
  shuffle : True
  num_workers : 1
  persistent_workers : True


model_config:
  embed_dim: 768

cluster_config:
  k: 1000
  bs: 50000
  lr: 0.1
  tol: 0.15
  num_search: 4
  k_sparse: 64

data_config:
  num_doc: 1000000
  num_samples: 100000
  windows: 96
  step: 64

generate_config:
  no_repeat_ngram_size: 6
  do_sample: True
  top_k: 50
  num_beams: 3
  bad_words_ids: null




seed: 87
