train_config:
  max_epoch : 6
  spilt : 0.95
  num_samples : null
  enc_lr : 5.e-5
  lm_lr : 1.e-5
  agent_lr : 3.e-4
  betas: [0.9, 0.99]
  weight_decay : 0.01
  topk : 1
  head : 2
  load_E : True

loader_config:
  batch_size : 2
  shuffle : True
  num_workers : 1
  persistent_workers : True


model_config:
  embed_dim: 768

cluster_config:
  k: 2000
  bs: 100000
  lr: 0.1
  tol: 1
  num_search: 4

data_config:
  num_doc: 100000
  num_samples: 100000
  windows: 96
  step: 64

generate_config:
  no_repeat_ngram_size: 6
  do_sample: True
  top_k: 50
  num_beams: 3
  bad_words_ids: null




seed: 87
